### ISSUE TITLE
Package Loading

### ISSUE THREAD

**Issue by constantin-zackl** [omnideconv/omnideconv#113]
When loading omnideconv this startup message keeps appearing: 
![image](https://user-images.githubusercontent.com/41090774/172019622-dd4dd7e5-2cc7-4e23-9f5a-f0b878123494.png)

I think it would make sense to decide for a one of the "extracts" and handle the imports accordingly to remove the message

**Comment by grst** [comment]
This is already addressed in #110, but not yet merged

**Comment by constantin-zackl** [comment]
Ah thanks okay :+1:
