### ISSUE TITLE
Object handling - assay selection

### ISSUE THREAD

**Issue by constantin-zackl** [omnideconv/omnideconv#122]
When providing objects as single cell input (sce, anndata) users can provide a cell_type_column name to extract the cell type annotation automaticly. However, what can not be specified is the assay/layer of the data to use. For example, SCEs typically contain a counts assay while normalized data is stored in assays called "logcounts", "tpm", "cpm", ... 

The function extracting the data does pick the first assay available here in line 235: https://github.com/omnideconv/omnideconv/blob/d2a50d355cb5dafb8342144acfc78af7504f267e/R/data_processing.R#L230-L238

The wrapper function calling this conversion does not pass an assay_name in line 439, therefore it will always be NULL. So, even if an object with the assays "counts" and "tmp" is provided, the "counts" assay will be used. 
https://github.com/omnideconv/omnideconv/blob/d2a50d355cb5dafb8342144acfc78af7504f267e/R/data_processing.R#L431-L441

My idea is to add an "assay" parameter to the `convert_to_matrix()` function (and therefore to `deconvolute()` and `build_model()`). 
The `singleCellExperiment_to_matrix()` function does already support this, the parameter just has to be passed. The anndata equivalent would require some changes as this is not implemented there yet.

**Comment by federicomarini** [comment]
+1 for the extra flexibility - It could be fairly simple to implement, I hope it would not bring in too much weight in the things downstream...

**Comment by federicomarini** [comment]
As an alternative - or at least as a default option if no assay name is provided - the function would use the **first** slot in the assays

**Comment by constantin-zackl** [comment]
> As an alternative - or at least as a default option if no assay name is provided - the function would use the **first** slot in the assays

This is how it is implemented currently, but as this parameter never gets passed anywhere it always is the first assay that is used at the moment

From a first look i also expect this to be fast to implement, but not sure about this.

**Comment by constantin-zackl** [comment]
This feature would be nice as i am mainly working with objects in SpaceDeconv and normalized data is typically saved in an additional assay. I could open a PR at some point, just let me now what you think. @grst @FFinotello @mlist @alex-d13 @LorenzoMerotto

**Comment by FFinotello** [comment]
I like this idea!

**Comment by constantin-zackl** [comment]
Merged with #127
