### ISSUE TITLE
singularity cannot be found.

### ISSUE THREAD

**Issue by sanghoonleepitt** [omnideconv/omnideconv#134]
Hi,

I am using a supercomputer in my university. I installed omnideconv and downloaded the singularity container to get the singularity is available in the R environment. But, I got an error that the installation of singularity can not be found. I think something is wrong in omnideconv.  Could you see the code and errors below and give me some advice to solve this issue?

[fangping@login0b ticket_12208]$ module load singularity/3.9.6
[fangping@login0b ticket_12208]$ **singularity pull --dir /ix/fangpingtest/ticket_12208 docker://cibersortx/fractions**

[fangping@login0b ticket_12208]$ srun -c 4 --pty bash
[[fangping@htc](mailto:fangping@htc)-1024-n0 ticket_12208]$ module load singularity/3.9.6
[[fangping@htc](mailto:fangping@htc)-1024-n0 ticket_12208]$ module load gcc/10.2.0 r/4.2.0
[[fangping@htc](mailto:fangping@htc)-1024-n0 ticket_12208]$ R

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
```

> old_path = Sys.getenv("PATH")
> Sys.setenv(PATH = paste("/ihome/crc/install/singularity/3.9.6/bin", old_path, sep = ":"))
> BulkMixtureFile <- "High_Resolution_Melanoma_TCGA_mixtures_Fig6ab.txt"
> SigMatrixFile <- "LM22.txt"
> ImmuneDeconv2Out_cibersortx <- omnideconv::deconvolute_cibersortx(BulkMixtureFile, SigMatrixFile , verbose=TRUE, container="singularity", container_path="/ix/fangpingtest/ticket_12208", input_dir=NULL, output_dir=NULL, display_extra_info=FALSE, label="none")

**Installation of singularity can not be found. Please check whether you can call 'docker' in the command line and get a help menu**
> system("singularity")
Usage:
singularity [global options...] <command>

Available Commands:
build Build a Singularity image
cache Manage the local cache
capability Manage Linux capabilities for users and groups
completion Generate the autocompletion script for the specified shell
config Manage various singularity configuration (root user only)
delete Deletes requested image from the library
exec Run a command within a container
inspect Show metadata for an image
instance Manage containers running as services
key Manage OpenPGP keys
oci Manage OCI containers
overlay Manage an EXT3 writable overlay image
plugin Manage Singularity plugins
pull Pull an image from a URI
push Upload image to the provided URI
remote Manage singularity remote endpoints, keyservers and OCI/Docker registry credentials
run Run the user-defined default command within a container
run-help Show the user-defined help for an image
search Search a Container Library for images
shell Run a shell within a container
sif Manipulate Singularity Image Format (SIF) images
sign Attach digital signature(s) to an image
test Run the user-defined tests within a container
verify Verify cryptographic signatures attached to an image
version Show the version for Singularity

Run 'singularity --help' for more detailed usage information.

```

Thank you, 
Sanghoon

**Comment by PelzKo** [comment]
@Whoever is fixing this: Please also change the error message so it does not tell the user to call "docker" but whatever is supplied as the container

**Comment by LorenzoMerotto** [comment]
Hello @sanghoonleepitt , 

There was actually an issue with the way the function checked if singularity was installed. 
We are currently working on it! Many thanks for the remark

**Comment by sanghoonleepitt** [comment]
@LorenzoMerotto, Thank you for your reply! I am going to wait until the issue is resolved.

**Comment by seb951** [comment]
Had the same problem. It is essentially due to this helper function (`check_container`) that checks if docker or singularity are properly installed: 
https://github.com/seb951/omnideconv/blob/29322c9404c13808c34649ad6c3258820be8eeac/R/helper.R#L22

This function (`check_container`) is called here: https://github.com/omnideconv/omnideconv/blob/29322c9404c13808c34649ad6c3258820be8eeac/R/CibersortX.R#L65
and here:
https://github.com/omnideconv/omnideconv/blob/29322c9404c13808c34649ad6c3258820be8eeac/R/CibersortX.R#L198

If you know that you have docker properly installed, a simple hack is to comment it out and reload both function that call it. Then it runs smoothly.

**Comment by LorenzoMerotto** [comment]
Fixing this in #173
