### ISSUE TITLE
packages "omnideconv" couldnot be  installed

### ISSUE THREAD

**Issue by hb755972333** [omnideconv/omnideconv#147]
Hi,
I installed omnideconv in the R environment. But, I got an error that the installation couldnot be installed. I think something is wrong in omnideconv. Could you see the code and errors below and give me some advice to solve this issue?

Moreover, when I install 64-bit miniconda, I got an error "Your current architecture is 64bit; however, this version of Python was compiled for 32bit." WhileI install 32-bit miniconda, I got an error "Your current architecture is  32bit; however, this version of Python was compiled for 64bit.  Thanks .

Here was the code and the errors:

>pak::pkg_install("omnideconv/omnideconv")
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
v Loading metadata database ... done                              
                                                                                            
> Will install 1 package.
> Will download 1 package with unknown size.
+ omnideconv   0.0.0.9000 [bld][cmp][dl] (GitHub: 6586f30)
i Getting 1 pkg with unknown size
v Cached copy of omnideconv 0.0.0.9000 (source) is the latest build
v No downloads needed, all packages are cached                      
i Packaging omnideconv 0.0.0.9000
v Packaged omnideconv 0.0.0.9000 (4.2s)                                         
i Building omnideconv 0.0.0.9000                                                
x Failed to build omnideconv 0.0.0.9000                                         
Error:                                                                          
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package 'omnideconv'
Full installation output:
* installing *source* package 'omnideconv' ...
staged installation is only possible with locking
** using non-staged installation
** R
Warning: unable to re-encode 'helper.R' lines 131, 182
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'omnideconv'
    finding HTML links ... done
    RefData                                 html  
    anndata_checkload                       html  
    anndata_is_identical                    html  
    anndata_to_singlecellexperiment         html  
    autogenes_checkload                     html  
    batch_ids_1                             html  
    batch_ids_2                             html  
    batch_ids_3                             html  
    bseqsc_config                           html  
    build_anndata                           html  
    build_model                             html  
    build_model_autogenes                   html  
    build_model_bayesprism                  html  
    build_model_bisque                      html  
    build_model_bseqsc                      html  
    build_model_cdseq                       html  
    build_model_cibersortx                  html  
    build_model_cpm                         html  
    build_model_dwls                        html  
    build_model_momf                        html  
    build_model_music                       html  
    build_model_scaden                      html  
    build_model_scdc                        html  
    bulk                                    html  
    calc_condition_number                   html  
    calculate_cell_embedding                html  
    cell_type_annotations_1                 html  
    cell_type_annotations_2                 html  
    cell_type_annotations_3                 html  
    check_and_install                       html  
    check_container                         html  
    check_credentials                       html  
    convert_to_matrix                       html  
    create_container_command                html  
    deconvolute                             html  
    deconvolute_autogenes                   html  
    deconvolute_bayesprism                  html  
    deconvolute_bisque                      html  
    deconvolute_bseqsc                      html  
    deconvolute_cdseq                       html  
    deconvolute_cibersortx                  html  
    deconvolute_cpm                         html  
    deconvolute_dwls                        html  
    deconvolute_momf                        html  
    deconvolute_music                       html  
    deconvolute_scaden                      html  
    deconvolute_scdc                        html  
    deconvolution_methods                   html  
    deescape_special_chars                  html  
    dot-bisque_patched_deconvolution        html  
    dot-bisque_patched_model                html  
    escape_special_chars                    html  
    get_cell_fractions_options              html  
    get_method_options                      html  
    get_signature_matrix_options            html  
    get_single_cell_expression_set          html  
    init_python                             html  
    install_all_python                      html  
    install_autogenes                       html  
    install_scaden                          html  
    make_barplot                            html  
    make_benchmarking_scatterplot           html  
    matrix_to_singlecellexperiment          html  
    normalize_deconv_results                html  
    plot_deconvolution                      html  
    python_available                        html  
    read_anndata                            html  
    required_packages                       html  
    save_as_h5ad                            html  
    scaden_checkload                        html  
    scaden_predict                          html  
    scaden_process                          html  
    scaden_simulate                         html  
    scaden_simulate_example                 html  
    scaden_train                            html  
    sces_are_identical                      html  
    set_cibersortx_credentials              html  
    set_python                              html  
    setup_singularity_container             html  
    single_cell_data_1                      html  
    single_cell_data_2                      html  
    single_cell_data_3                      html  
    singlecellexperiment_to_anndata         html  
    singlecellexperiment_to_matrix          html  
    transform_and_save_bulk                 html  
    transform_and_save_single_cell          html  
    verbose_wrapper                         html  
    write_anndata                           html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'omnideconv':
 .onLoad failed in loadNamespace() for 'omnideconv', details:
  call: NULL
  error: Your current architecture is 32bit; however, this version of Python was compiled for 64bit.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/haobo/AppData/Local/Temp/RtmpAR8eKU/pkg-lib3d141ba7502f/omnideconv'

Thanks in advance.

**Comment by mlist** [comment]
At first glimpse this looks more like an issue with your miniconda installation than with omnideconv. Can you confirm that your miniconda installation and reticulate otherwise work fine? I suggest you run a small python script through reticulate to test: https://rstudio.github.io/reticulate/

**Comment by mlist** [comment]
That's a fair point. We haven't had much experience with setting up omnideconv under Windows yet. I would still say your best chance is to first confirm that your miniconda / reticulate setup is working correctly before moving on with the installation. Alternatively you could spin up an instance of ubuntu with [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install)  @LorenzoMerotto do you have any comment here?

**Comment by LorenzoMerotto** [comment]
@hb755972333 I have just installed omnideconv on my Windows machine (without using WSL), it worked all fine and the necessary packages were installed. 
One thing that could help in this case is running R as an administrator since it could be that `reticulate` has not all the necessary rights to load the environments. Could you please try it? 
 Alternatively, the solution would be to manually set up a python environment, or to use WSL. Unfortunately reticulate has always some bugs with Windows

**Comment by shrvi** [comment]
Hi, I receive a similar error with ubuntu as well, I get the same error for the package omnideconv /spacedeconv

Can you please help? 

DONE (pak)

The downloaded source packages are in
        ‘/tmp/RtmpYCedTT/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

    pak::pkg_install("omnideconv/spacedeconv", dependencies=TRUE)
    ! Using bundled GitHub PAT. Please add your own PAT using gitcreds::gitcreds_set().
    ✔ Loading metadata database ... done

→ Will install 13 packages.
→ All 13 packages (6.26 MB) are cached.

    CARD 1.1 [bld][cmp] (GitHub: 2d64b91)
    concaveman 1.1.0 [bld] + ✔ libgdal-dev, ✔ gdal-bin, ✔ libgeos-dev, ✔ libproj-dev
    Giotto 4.0.2 [bld][cmp] (GitHub: 7b8ad7b)
    GiottoClass 0.1.3 [bld][cmp] (GitHub: fca6eb3)
    GiottoVisuals 0.1.4 [bld][cmp] (GitHub: e3feee4)
    MCMCpack 1.7-0 [bld][cmp]
    metafor 4.4-0 [bld]
    MuSiC 0.3.0 [bld][cmp] (GitHub: 7b18b03)
    omnideconv 0.0.0.9000 [bld][cmp] (GitHub: 29322c9)
    RcppML 0.3.7 [bld][cmp]
    spacedeconv 0.0.1.0000 [bld][cmp] (GitHub: cd33d4e)
    spacexr 2.2.1 [bld][cmp] (GitHub: 90cc7dc)
    V8 4.4.1 [bld][cmp] + ✔ libnode-dev

✔ All system requirements are already installed.

ℹ No downloads are needed, 13 pkgs (6.26 MB) are cached
ℹ Building spacedeconv 0.0.1.0000
ℹ Building omnideconv 0.0.0.9000
ℹ Building metafor 4.4-0
ℹ Building MCMCpack 1.7-0
ℹ Building RcppML 0.3.7
ℹ Building V8 4.4.1
ℹ Building GiottoClass 0.1.3
✖ Failed to build spacedeconv 0.0.1.0000
Error:
! error in pak subprocess
Caused by error in stop_task_build(state, worker):
! Failed to build source package spacedeconv.
Type .Last.error to see the more details.

    .Last.error

    <callr_error/rlib_error_3_0/rlib_error/error>
    Error:
    ! error in pak subprocess
    Caused by error in stop_task_build(state, worker):
    ! Failed to build source package spacedeconv.

    Backtrace:

        pak::pkg_install("omnideconv/spacedeconv", dependencies = TRUE)pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …err$throw(res$error)

    Subprocess backtrace:

        base::withCallingHandlers(cli_message = function(msg) { …get("pkg_install_do_plan", asNamespace("pak"))(...)proposal$install()pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …base::withCallingHandlers({ …pkgdepends:::handle_events(state, events)pkgdepends:::handle_event(state, i)pkgdepends:::stop_task(state, worker)pkgdepends:::stop_task_build(state, worker)

        base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …| base::signalCondition(cond)global (function (e)`

**Comment by alex-d13** [comment]
The dependencies and installation requirements have change a lot since opening this issue. Please try again with our new version, if the error persists feel free to open this issue again.
