### ISSUE TITLE
Question: does this package support gene expression inference (in addition to proportion inference)?

### ISSUE THREAD

**Issue by grisaitis** [omnideconv/omnideconv#150]
Some methods like cibersortx and bayesprism infer sample-specific gene expression from bulk RNA-seq and scRNA-seq reference data. For example, cibersortx offers this with their `hires` docker image. 

My question is - does this package have an interface for producing and consuming that output?

Asking because I couldn't find information about this in the docs / readme. Apologies if I missed something.

**Comment by mlist** [comment]
As far as I know we don't support such features at the moment. Our focus is on cell type composition.

**Comment by grisaitis** [comment]
Thanks for replying! 

Is gene expression inference something you're interested in adding? Or maybe as a separate project?

Asking because I'm working on a project in this area - evaluating methods for cell type-specific gene expression deconvolution applied to certain cancers. I love the approach you all take here of creating a common interface, wrapping various methods.

**Comment by mlist** [comment]
This is not our focus but would be a welcome extension to our current package. If you are interested in contributing here you could make a pull request with the additional features included? That would be very welcome.
