### ISSUE TITLE
Installing omnideconv causes error.

### ISSUE THREAD

**Issue by jacobHog** [omnideconv/omnideconv#169]
Hello,

I am attempting to install omnideconv, but I am encountering unexpected errors during the installation process.

I am working on a HPC system where I have user rights but lack administrator privileges. To manage my environments, I use Conda. While I typically install packages through Bioconductor or CRAN, I understand that omnideconv cannot be installed from those repositories at this time, as mentioned on your homepage.

Here is the sequence of steps I've followed to set up my environment and attempt the installation of omnideconv:

conda create -n omnideconv_environment r-base=4.2.3
# Open R and install:
install.packages("pak")
library(pak)
install.packages("reticulate")
library(reticulate)
pak::pkg_install("omnideconv/omnideconv", dependencies = TRUE)

However, during the installation process, I encountered the following error:

> pak::pkg_install("omnideconv/omnideconv", dependencies = FALSE)
                                                                  
→ Will install 1 package.
→ The package (0 B) is cached.
+ omnideconv   0.0.0.9000 [bld][cmp] (GitHub: a3587a0)
ℹ No downloads are needed, 1 pkg is cached
ℹ Packaging omnideconv 0.0.0.9000
✖ Failed to create source package omnideconv 0.0.0.9000          
                                                                 
── Standard output ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning: unknown option ‘--no-lock’                              
* checking for file ‘/tmp/usertmp/RtmpHEbOe8/X/omnideconv/omnideconv-omnideconv-a3587a0/DESCRIPTION’ ... OK
* preparing ‘omnideconv’:
* checking DESCRIPTION meta-information ...Warning in person1(given = given[[i]], family = family[[i]], middle = middle[[i]],  :
  It is recommended to use ‘given’ instead of ‘middle’.
Warning in person1(given = given[[i]], family = family[[i]], middle = middle[[i]],  :
  It is recommended to use ‘given’ instead of ‘middle’.
 ERROR
Authors@R field gives more than one person with maintainer role:
  Lorenzo Lorenzo.Merotto@uibk.ac.at Merotto [aut, cre]
  Alexander alex.dietrich@tum.de Dietrich [aut, cre]
Authors@R field gives no person with maintainer role, valid email
address and non-empty name.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
Error:                                                           
! error in pak subprocess
Caused by error in `stop_task_package_build(state, worker)`:
! Failed to create source package omnideconv from source tree at /scratch/usertmp/RtmpHEbOe8/file3179212209761/src/contrib/omnideconv_0.0.0.9000_a3587a0.tar.gz-t
Type .Last.error to see the more details.

I would greatly appreciate any guidance or assistance you can provide to resolve this issue. Please let me know if you need any further information from my end.

**Comment by alex-d13** [comment]
Hi,

Thanks for reaching out. The error appeared due to a bug that was introduced during my latest change. Should be fixed now, could you check again?

Best,
Alex

**Comment by jacobHog** [comment]
Hi Alex,

Thank you for replying so fast.
I get this error now:

> pak::pkg_install("omnideconv/omnideconv", dependencies = TRUE)
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
✔ Loading metadata database ... done                              
Error:                                                                                      
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* omnideconv/omnideconv: dependency conflict
Type .Last.error to see the more details.


Output from .Last.error:

<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* omnideconv/omnideconv: dependency conflict
---
Backtrace:
1. pak::pkg_install("omnideconv/omnideconv", dependencies = TRUE)
2. pak:::remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { …
2. get("pkg_install_make_plan", asNamespace("pak"))(...)
3. prop$stop_for_solution_error()
4. private$plan$stop_for_solve_error()
5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
7. | base::signalCondition(cond)
8. global (function (e) …

**Comment by alex-d13** [comment]
Mh, so it seems like some packages are conflicting during installation, which does not usually happen if omnideconv is installed in a clean environment. From the error message above its not clear, which packages are causing the problem, is it possible for you to get more information here?

**Comment by jacobHog** [comment]
Please specify if you have a specific command for me to troubleshoot with.
I went ahead and tried dependencies = FALSE and got this:

> pak::pkg_install("omnideconv/omnideconv", dependencies = FALSE)
                                                                  
→ Will install 1 package.
→ The package (0 B) is cached.
+ omnideconv   0.0.0.9000 [bld][cmp] (GitHub: a744eb3)
ℹ No downloads are needed, 1 pkg is cached
✔ Got omnideconv 0.0.0.9000 (source) (19.54 MB)
ℹ Packaging omnideconv 0.0.0.9000
✔ Packaged omnideconv 0.0.0.9000 (3.8s)                          
ℹ Building omnideconv 0.0.0.9000                                 
✖ Failed to build omnideconv 0.0.0.9000 (1.4s)  

From .Last.error I got this:
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package omnideconv.
---
Backtrace:
1. pak::pkg_install("omnideconv/omnideconv", dependencies = FALSE)
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::handle_events(state, events)
 7. pkgdepends:::handle_event(state, i)
 8. pkgdepends:::stop_task(state, worker)
 9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
11. | base::signalCondition(cond)
12. global (function (e) …

**Comment by alex-d13** [comment]
Could you try to install omnideonv with `remotes`? So sth like this:

`remotes::install_github("omnideconv/omnideconv")`

**Comment by jacobHog** [comment]
Hi,

That got me into a ~45 minute installation which ended with an error.. Prior to the remotes::install_github installations the errors occured after a few seconds, so hopefully this new bug is an improvement :) What version of R is recommended? I got this error:

ERROR: dependency ‘SCOPfunctions’ is not available for package ‘omnideconv’
* removing ‘/home/jeh/miniforge3/envs/omnideconv_environment/lib/R/library/omnideconv’
Warning messages:
1: package ‘MAST’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘/scratch/usertmp/RtmptA5OQ4/file9fbcd18a3a9bb/SCOPfunctions_0.0.0.9000.tar.gz’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/scratch/usertmp/RtmptA5OQ4/file9fbcd3804ea39/omnideconv_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by alex-d13** [comment]
Hi,

we are recommending R >=4.1.0.
In your case, it seems like `SCOPfunctions` and `MAST` could not be installed properly. Can you try to install them separate of omnideconv first (see here: https://github.com/CBMR-Single-Cell-Omics-Platform/SCOPfunctions and https://bioconductor.org/packages/release/bioc/html/MAST.html)?

**Comment by jacobHog** [comment]
Hi,

Alright I just attempted to install mast and scopfunctions using install.packages (using R v4.3.0) but it kept saying the R version was not suitable for those packages...

Then I did this:

conda create -n omnideconv_environment r-base=4.3.0 bioconductor-mast r-scopfunctions
conda activate omnideconv_environment

# Open R and install:
install.packages("reticulate")
install.packages("remotes")
remotes::install_github("omnideconv/omnideconv")
library(reticulate)
library(remotes)
library(omnideconv)

This successfully installed omnideconv.

I have not tested if it works yet, and i do not know if the dependencies are installed using the remotes::install_github("omnideconv/omnideconv").
For now the ticket is "solved", but I will keep it open until I have tested 👍 
Thanks for the help, Alexander

**Comment by alex-d13** [comment]
Hi,

Did you test if it works?

**Comment by jacobHog** [comment]
Hi, 

Thanks for follow up.
Yes it seems that the installations works, however I have held back a follow up questions because I work in a core facility where projects change fast.

- I am trying to use the `omnideconv::build_model(single_cell_data, cell_type_annotation, method = "dwls")` to create the signature matrix, but I am very uncertain whether it is going as expected.
# Workflow:
1. I create a single_cell_data matrix which is a data.frame which looks like this:

![image](https://github.com/omnideconv/omnideconv/assets/91322516/9d3700da-8af6-4f6b-a610-e59230be568a)

2. I create a cell_type_annotation list that contains this:

![image](https://github.com/omnideconv/omnideconv/assets/91322516/02bcff12-bbed-467c-91bd-cc95a3176f9d)

3. I make a sanity check to see if the expected length of the list is equal to the length of celltypes between the two objects
`length(cell_type_annotation) == length(colnames(single_cell_data))`. (TRUE should indicate that we're on the right track).

To my understanding the dwls method is downloaded during the `remotes::install_github("omnideconv/omnideconv")`, right? I do not get an error or warning when running `omnideconv::build_model`, but I ever get an output (even after 12 hours computing with 64 cores running). 

So I guess my questions is, how do we install these tools (if they are not already installed during the github installation)? The methods bisque, bseqsc, cpm, momf, scdc can not be installed through conda, and cibersortx has this request-required download.

**Comment by alex-d13** [comment]
Hi,

You managed to pick the one method that stands out as the slowest one, especially with large datasets :D
We tried to improve the runtime of this methods with improved parallelization, which you can activate with the parameter `dwls_method = "mast_optimized"` in the `build_model_dwls()` function. 
Could you give this a try?

Apart from that, your understanding that methods are installed during `remotes::install_github("omnideconv/omnideconv")` is correct. CIBERSORTx runs via a Docker or Apptainer container and you need to request an access token on their website to use it via omnideconv.

Best,
Alex

**Comment by jacobHog** [comment]
Hi,

I can see that I made a mistake with the build_model, I did not furfill the requrement: "_the A vector of the cell type annotations. Has to be in the same order as the samples in single_cell_object_." and also I forgot the bulk matrix... [https://rdrr.io/github/PelzKo/immunedeconv2/man/build_model.html](url)

After correction the code looks like this:
`omnideconv::build_model(single_cell_object = single_cell_data, cell_type_annotations = cell_type_annotation, method = "dwls", bulk_gene_expression = bulk_expression_matrix)` 
However I get this error 
"mast was chosen because multiple values were supplied for "dwls_method"
Error in DWLS::buildSignatureMatrixMAST(scdata = single_cell_object, id = cell_type_annotations,  : 
  unused argument (ncores = ncores)"
  But I see no mention of any ncores? [https://rdrr.io/github/PelzKo/immunedeconv2/man/build_model.html](url)


Additionally,
if I use your suggestion:

`build_model_dwls(single_cell_object = single_cell_data, cell_type_annotations = cell_type_annotation, dwls_method = "mast_optimized")`
then I get this error:
Error: 'buildSignatureMatrixMASTOptimized' is not an exported object from 'namespace:DWLS'

I am not sure if I am missing some obvious points, or am I being challenged much?

**Comment by LorenzoMerotto** [comment]
Hello @jacobHog 
I'm jumping in the thread with a couple suggestions.
What usually happens is that IF the methods are not installed uponm first installation, they will be installed when the function is first called. 

However, we made some updated to DWLS, which is now hosted on out GitHub. What I suspect is that you have an older version of DWLS installed, which is not compatible with the newer parametrers.

I suggest you run `remotes::install_github('omnideconv/DWLS')` and try to run the code once again

**Comment by jacobHog** [comment]
Hi @LorenzoMerotto 

Thank you for the inputs.
The suggestion made it work and it created something that looks like a signature file, and I also got an output from using omnideconv::deconvolute. (Do you guys have a nice way of plotting this? Either something like the immunodeconv plotting shown below or something with gradient coloring? 
![image](https://github.com/omnideconv/omnideconv/assets/91322516/b3d9263b-4fe5-4e68-beca-9337472deed1)
)
So far I get an output using the dwls function, but I do not recommend using other suggestions except for this:
`dwls_signature_file <- build_model_dwls(single_cell_object = single_cell_data, cell_type_annotations = cell_type_annotation, dwls_method = "mast_optimized")`

I tried the other methods that does not utilize the mast_optimized value, but they never complete (+4 hours with 128 gb ram and 64 cores without results). 

I will have to try other deconvolution methods as well, such as cibersort. I have been using BASE from immunodeconv for most mouse experiments. 
Thanks @alex-d13 and @LorenzoMerotto for helping :)
