### ISSUE TITLE
CIBERSORTx and Windows

### ISSUE THREAD

**Issue by LorenzoMerotto** [omnideconv/omnideconv#177]
Hello team, 
I decided to open an issue here since it will simplify the discussion. 
We have decided to guarantee support for omnidecov only for Unix systems due to dependencies limitations. 
However, I think it's good to test if the package works on Windows too. 

I was trying to run CIBERSORTx using docker on my laptop, and it looked like the docker installation could not be found. 
I then had a look at the code and I noticed the function `check_container()` (code [here](https://github.com/omnideconv/omnideconv/blob/994e5037904759166affd9b25f0b0d099c8b7816/R/helper.R#L22))

Specifically, the portion: 

```
if (container == "docker") {
    command <- "docker"
  }
  else {
    command <- "singularity instance list"
  }
  container.available <- (system(command, ignore.stdout = TRUE, 
    ignore.stderr = TRUE) == 0)
  if (!container.available) {
    message(paste0("Installation of ", container, " can not be found. Please check whether you can ", 
      "call '", container, "' in the command line and get a help menu"))
    return(FALSE)
  }
  ```
  While this function works on Unix, it does not on Windows even if the docker installation is available. 
  If I run `var <- system('docker')` I get the standard docker output, and `var=0` 
  If I run it with  `var <- system('docker', ignore.stdout = TRUE)`, then I get `var = 2`, and therefore the previous check fails
  
  I think we should remove the constraint ` ignore.stdout = TRUE`, but I want to hear your opinion on the matter. Should we maybe do a Windows-specific check? 
  
  Tagging @alex-d13 , @PelzKo , @czackl , @bernheder

**Comment by bernheder** [comment]
If I read the function right, then this function returns FALSE also when Docker is installed but just isn't running.
So there could be many reasons why the docker command fails which are possibly not so easy to detect. 

How about just removing this function? 😄  
I would argue it is not omnideconv's responsibility to check if docker/singularity is correctly installed. A
nother strategy would be to just try to run in, and should anything go wrong just returning the error.

For example when you try to run docker without the docker daemon running you get this error:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
This would be enough for the user to figure out what is wrong.

**Comment by alex-d13** [comment]
I like the suggestions of Bernhard.
However, now that we have also seen that the python based methods give us some issues when we try to install them via conda on windows, I am not sure how far we can really support omnideconv on windows..

**Comment by LorenzoMerotto** [comment]
@bernheder Actually the problem just lies in the option `ignore.stdout=TRUE`
If we set it to TRUE, docker is correctly found and the signature building/deconvolution can start without issues

I don't understand why the standard output is set to FALSE, and I think changing it to TRUE wouldn't hurt the method

**Comment by bernheder** [comment]
ok,  I also don't understand why this is happening. But at least the fix is easy in this case 😅
