### ISSUE TITLE
Docker alternatives for cibersortx

### ISSUE THREAD

**Issue by grst** [omnideconv/omnideconv#39]
Feel free to address if you have time, otherwise consider it as a reminder for the future. 

Cibersort currently runs with docker. Docker, however, is getting less and less popular in favor of Singularity and Podman.
The advantage of those two container engines is that they don't require sudo rights on the system and are, therefore, much more suitable for shared environments. 

Podman should be very easy to support - It's essentially just replacing `docker run` with `podman run`. 
For singularity it may be more tricky: The container needs to be converted into singularity format, which usually works well except when it doesn't.

**Comment by LorenzoMerotto** [comment]
Singularity was succesfully implemented

**Comment by alex-d13** [comment]
Updated Singularity to Apptainer in #172
