### ISSUE TITLE
Input sanity check

### ISSUE THREAD

**Issue by FFinotello** [omnideconv/omnideconv#58]
In the long run, it might be a good idea to introduce a module to sanity-check the input data before building the signatures.

In principle, we don't need to keep all the cells in each cell-type cluster, but we might want to eliminate those that behave like outliers (e.g. miscalled cells, doublets, low-quality cells, "meta-states").

To this end, we could use some methods for automatic cell classification and identify only the robustly annotated ones (e.g. through a consensus, majority-rule approach). 
But we would need some "open" tools that can be used for various cell types, tissues, organisms.
It might be good to start tracking what is available in the literature.

An alternative easier approach would be to use some similarity measure like in clustering, to really spot (and discard) only extreme outliers regardless of their annotation.

What do you guys think?

**Comment by grst** [comment]
superseded by #100
