### ISSUE TITLE
More details about the methods

### ISSUE THREAD

**Issue by PelzKo** [omnideconv/omnideconv#77]
**Smart-seq2 or 10x data**
- Bisque: 10x was used, but there was no mention that Smart-seq2 would not work
- CIBERSORTx: 10x was used, microarray data was used, Smart-seq2 was used
- DWLS: no details, 10x was used
- MOMF:  bulk: Level-3 Illumina Hiseq data was used, sc-data: GPL15520 | Illumina MiSeq (Homo sapiens), GPL18573 | Illumina NextSeq 500 (Homo sapiens), the MuSiC data was also used
- Scaden: microarray data can be used (as described in the Discussion part of the paper), mainly 10x data was used for sc-data and GPL11154 | Illumina HiSeq 2000 (Homo sapiens) for the bulk data
- MuSiC: Smart-seq2, 10x and Illumina HiSeq 2000 and 2500 were used
- AutoGeneS: Smart-seq2, GPL2827 | VUMC MACF human 30K oligo v44 (array)
- SCDC: 10x and Illumina HiSeq 2000 and 2500 were used
- BSeq-sc: inDrop Illumina Hiseq 2500 (paired end) and GPL11154 | Illumina HiSeq 2000 (Homo sapiens)
- CPM: GPL19057 | Illumina NextSeq 500 (Mus musculus) and GPL17021 | Illumina HiSeq 2500 (Mus musculus)
- CDSeqR: GPL16791 | Illumina HiSeq 2500 (Homo sapiens), GPL17021 | Illumina HiSeq 2500 (Mus musculus), GPL18573 | Illumina NextSeq 500 (Homo sapiens), Smart-seq2, 10x

**Type of expression levels to be used (counts, TPM, library-normalized counts, log or natural scale)?**
- Bisque: counts are required for single cell and bulk data. They are converted to CPM by bisque and zero variance genes are filtered out
- CIBERSORTx: no mention what is needed, they used TPM/10 and more steps (see Methods -> Single-cell signature matrix construction in the paper) for the sc-data, no information about the bulk data (but probably the same treatment)
- DWLS: no mention what is needed, they used UMI counts for the sc-data and FPKM values for the bulk data
- MOMF: raw gene expression count should be used, as normalization can bring biases
- Scaden: no mention what is needed, they normalized the sc-data to library size and filtered cells with less than 500 genes and genes in less than 5 cells; the bulk data was used raw 
- MuSiC: read counts are used, RPKM is possible if estimates of cell type specific total RNA abundance can be provided (e.g., estimated from another data set), TPM is NOT possible
- AutoGeneS: no mention what is needed, TPM or RPKM was used
- SCDC: raw counts are needed for sc and bulk
- BSeq-sc: no mention what is needed, They multiplied the TPM profiles of the cells within a cell type by their mean total counts for the sc-data, no mention about bulk data so probably counts
- CPM: no mention what is needed, "Absolute profiles were transformed into "relative" profiles using a common control profile as the normalizer, where the control profile was pooled from the PBS-treated mice. Relative profiles were calculated using log-transformed infected and control samples."
- CDSeqR: no mention what is needed, they used RPKM

**Other important stuff**
- Bisque: cell populations are equally represented in single-cell and bulk RNA sequencing of the same tissue samples; at least 3 sc-samples
- CIBERSORTx: Batch correction greatly improved the accuracy
- DWLS: All cell types expected in the bulk data are also represented in the single-cell data (the converse need not be true), MAST for smaller sc-data sets, Seurat for larger ones
- MOMF: -
- Scaden: -
- MuSiC: -
- AutoGeneS: -
- SCDC: -
- BSeq-sc: Their signature creation method normalizes and scales the input data, so that should be kept in mind when using other signature matrices with the BSeq-sc deconvolution method
- CPM: Might lose power with lower sequencing depth (supplementary note 1 of the paper); they assume low quality cells are already removed from the sc-data
- CDSeqR: -

**Comment by grst** [comment]
What do we do with this information? Was this integrated into the documentation anywher?
